### Variables
# @url_base=http://localhost:8080
@url_base=https://sds4-backend-marcelo.herokuapp.com
@route=sales

### List all sellers
GET {{url_base}}/{{route}}

### List sellers pag 1 
GET {{url_base}}/{{route}}?page=0

### List sellers pag 2 
GET {{url_base}}/{{route}}?page=1

### List sellers pag 9 
GET {{url_base}}/{{route}}?page=8

### List sellers pages 1, 5 items 
GET {{url_base}}/{{route}}?page=0&size=5

### List sellers pages 1, 20 items  
GET {{url_base}}/{{route}}?page=0&size=20

### List sellers 10 items, sorted by data asc
GET {{url_base}}/{{route}}?size=10&sort=date

### List sellers 10 items, sorted by data desc
GET {{url_base}}/{{route}}?size=10&sort=date,desc