### Variables
#url local
@url_base=http://localhost:8080
# url Heroku
# @url_base=https://sds4-backend-marcelo.herokuapp.com

@route=sales/amount-by-seller

### List amount sales by seller
GET {{url_base}}/{{route}}
